ynput/ayon-nuke

- client/ayon_nuke/api/constants.py
- client/ayon_nuke/api/lib.py
When trying to save scenes that contain OpenPype UUIDs in representations Nuke was catching this error and not allowing you to save the scene:
```
Traceback (most recent call last):
File "/sw/nuke/15.0v4/plugins/nuke_internal/callbacks.py", line 92, in onScriptSave
_doCallbacks(onScriptSaves)
File "/sw/nuke/15.0v4/plugins/nuke_internal/callbacks.py", line 46, in _doCallbacks
f[0](*f[1],**f[2])
File "/home/lmenga/.local/share/AYON/addons/nuke_0.2.4-ax.2/ayon_nuke/api/lib.py", line 844, in check_inventory_versions
for repre_entity in repre_entities:
File "/pipe/ayon/release/current/dependencies/ayon_api/server_api.py", line 5967, in get_representations
for parsed_data in query.continuous_query(self):
File "/pipe/ayon/release/current/dependencies/ayon_api/graphql.py", line 380, in …
```
> Ignore containers with invalid UUID in representation

- client/ayon_nuke/api/lib.py
- client/ayon_nuke/api/plugin.py
Address #9 
I Implemented the solution suggested by @BigRoy on the associated issue which makes perfect sense:
* scoped the anatomy resolve to the required scoped template when creating a Write node
* No more resolving all templates when we use a single entry
1. Set broken Anatomy preset for something irrelevant to the Write node creation
(note additional `]` after variant)
2. Open Nuke and create a Write node from AYON -> Create
3. Ensure a write node get properly created despite part of the Anatomy being wrong
> Fix write node creation while broken project Anatomy.

- client/ayon_nuke/api/lib.py
- client/ayon_nuke/plugins/publish/validate_script_attributes.py
Workfile resolution and FPS is now set using the current task's entity attribute instead of from the parent folder entity.
I didn't test it.
Create a folder with a task where the task has different FPS and resolution.
1. Create new workfile - settings should adhere to task attributes
2. Use "Reset resolution" and "Reset frame range" menu actions - it should set it using the task attributes
3. Publishing validations should also adhere to the task attributes, not the folder entity attributes. (If there are any validators for that.)
> Use task attributes for WorkfileSettings

- client/ayon_nuke/api/__init__.py
- client/ayon_nuke/api/colorspace.py
- client/ayon_nuke/api/constants.py
- client/ayon_nuke/api/lib.py
- client/ayon_nuke/api/plugin.py
- client/ayon_nuke/api/utils.py
- server/settings/common.py
- server/settings/imageio.py
After adding support for context-specific anatomy token resolution in color management display and view options, we must now ensure value validation and provide fallback options. We're introducing a semicolon separator in values, allowing for multiple options where the order is important.
- colorspace methods were moved from lib to new nuke API module `colorspace.py`. Some of those function might need to move into core addon but for now lets keep them here. 
- version up dev number in package.py
- deploy addon version to your server and bundle
- make sure core colormanagement is enabled
- notice hints on `ayon+settings://nuke/imageio/viewer/display` 
- When conducting this testing, it is important to note that a published ocio config may not be present in your task context. Our objective …
> Display and View fallback options for settings and api

- client/ayon_nuke/api/plugin.py
The {output} anatomy keyword is now respected even if there is only one Extract Review Intermediate profile.
Having the published output as a one and only imagery in the folder helps apps Like Hiero to not get confused while searching for versions.
resolves https://github.com/ynput/ayon-nuke/issues/32
1. Make sure you have only one Extract Review Intermediate profile
2. Set anatomy render directory template to ```{root[work]}/{project[name]}/{hierarchy}/{folder[name]}/publish/{product[type]}/{product[name]}/{@version}/<_{output}>```
3. Publish Nuke render
4. Check publish folder structure
> Publishing review intermediates - always add anatomy output keyword

- client/ayon_nuke/api/lib.py
Ayon uses onScriptSave callback to update nodes' colors. If this fails by any reason, artist is not able to save the file.
Nuke sometimes fails on getting knob type needed in ```read_avalon_data```. This can result in artisn not being able to open workfile. Reason unknown, hard to test.
Changes allow artist to continue working.
Might close https://github.com/ynput/ayon-nuke/issues/33
1. Launch Nuke, open Workfile
2. Make changes
3. Stop server
4. Save file with Control + S
> Nuke behavior more resilient

- client/ayon_nuke/addon.py
Fixes #24 
- Sets `AYON_LOG_NO_COLORS` to `1` in `add_implementation_envs` in `NukeAddon` class
1. Open Nuke from AYON
2. The logs appear correctly
> Disable AYON_LOG_NO_COLORS in prelaunch hook

- client/ayon_nuke/plugins/load/load_gizmo.py
Fixes: #38 
- Add `lensDistortion` as product type that can be loaded as a gizmo in Nuke.
1. Publish a lensDistortion product from 3DE
2. Open Nuke
3. Open the loader and right click > load gizmo on the published lens distortion
> Add lensDistortion product type for loading gizmo

- client/ayon_nuke/api/lib.py
Sets the default position of the imported nodes to 0,0 if there are no nodes in the script
1. Delete everything
2. Import nuke nodes via the Loader
> find_free_space_to_paste_node errors if the script is completely empty

- server/settings/gizmo.py
- server/settings/scriptsmenu.py
resolve #44 
1. Custom Tools in Nuke should now work with the default settings
2. Everything should work as before.
> Fix deprecated default settings in `Custom Tools` and `Gizmo Menu`

- client/ayon_nuke/plugins/publish/collect_nuke_instance_data.py
- client/ayon_nuke/plugins/publish/extract_review_intermediates.py
- package.py
Use stagingDir on instance only if it is explicitly set as custom, in other case fall back to old implementation which produces baking script next in `work/../renders`.
This solves issue in `extract_review_intermediates` when now there was `stagingDir` on instance suddenly. This resulted in creation of baking script in `tempdir` which got purged at the end of publishing via `Clean Up` plugin.
This PR is variant of similar issue in Maya https://github.com/ynput/ayon-maya/pull/212
1. publish in Nuke via Deadline
2. baking step shouldnt fail
> Fix use of stagingDir

- package.py
Changed the core addon requirement from ">=1.0.13" to ">1.0.13" to ensure compatibility with newer versions only.
> Update version constraints for core addon

- client/ayon_nuke/api/colorspace.py
[Here](https://github.com/ynput/ayon-nuke/issues/59) the related issue.
In ACES 1.3 some of the colorspaces returned by `nuke.getColorspaceList` are in the form of a single string containing the colorspace name and its aliases separated by the tab character "\t" or a comma. E.g. `"ACES2065-1\t\taces2065_1,ACES - ACES2065-1,lin_ap0"`. This was not being taken in to account when adding colorspaces to the `results` list. 
For instance, here some of the resulting colorspace list without the fix: 
```python
[
"default (Gamma2.2)",
"aces_interchange",
"cie_xyz_d65_interchange",
"color_picking",
"color_timing",
"compositing_log",
"data",
"matte_paint",
"scene_linear",
"texture_paint",
"ACES2065-1\t\taces2065_1,ACES - ACES2065-1,lin_ap0",
"ACEScc\t\tACES - ACEScc,acescc_ap1",
"ACEScct\t\tACES - …
```
> Fix returned colorspace list in `get_colorspace_list` - AY-7415

- client/ayon_nuke/plugins/load/load_clip.py
- package.py
- server/settings/loader_plugins.py
Resolve: https://github.com/ynput/ayon-hiero/issues/12
Resolve: https://github.com/ynput/ayon-hiero/issues/29
Adjusted:
These changes needs to be tested alongside https://github.com/ynput/ayon-core/pull/1109
1. Publish plates with `speed-change (positive+negative)`, `freeze frames` and `TimeWarp` from an Editorial DCC
2. Gather published plates in `Nuke`
3. Ensure the working ranges match
> Fix retime gathering from Nuke (freeze frame, linear speed and TimeWarp)

- client/ayon_nuke/api/plugin.py
- Added early return for no selection case.
- Simplified logic to raise error only if selected nodes are missing.
- Handled headless mode by defaulting pre_create_data when absent.
closes #56 
1. have activated workfile template building templates at your project
2. have Create placeholder in template
3. build templates and see that creator placeholder is working again.
> Improve selection handling in NukeWriteCreator

- client/ayon_nuke/api/lib.py
- server/settings/conversion.py
- server/settings/gizmo.py
resolve #46 
> [!Note]
> Changes in this PR are inspired by the UX of the [`Shelves Manager`](https://ayon.ynput.io/docs/addon_houdini_admin#shelves-manager) in Houdini  addon settings.
> I've realize that Houdini docs are abit old.
> <details><summary>so here's a screenshot</summary>
>
> ![image](https://github.com/user-attachments/assets/a62102f1-be05-44d0-a99c-b353ecc063e0)
> </details>
Settings:
- Mode 1: Add a Gizmo Directory Path
- Mode 2: Add Gizmos By definitions
1. Test `copy settings` from older version.. values from older addon version should be propagated properly to the new version.
2. Try using different options `Gizmo Menu`. e.g. use `gizmo directory path`, use `gizmo definition` list.
3. Try using [template keys](https://ayon.ynput.io/docs/admin_settings_project_anatomy/#av …
> Easier `Gizmo Menu` settings

- client/ayon_nuke/api/colorspace.py
Viewer settings is now correctly applied even for Nuke 13.2 verison. 
Updated the colorspace knob from "monitorLut" to "monitorOutLUT" for accurate color space fetching. This change improves the reliability of getting display and view colorspaces.
1. Install Nuke 13.2
2. add the version to your application addon settings and assign it in your active applications at a project. 
3. Open the nuke and see that no popup message is not blocking the nuke session at launch.
> Applying correctly viewer colorspace from settings

- client/ayon_nuke/plugins/load/load_ociolook.py
Changes on the Nuke `ociolook` loader:
* Ensure multiple chained LUT published are properly loaded
* Fix the `invert_direction` LUT attribute for the `OCIOFileTransform` nuke node
This changes would be backward compatible with `ociolook` product from previous iterations.
To test the multiple/chained LUT feature, please refer to : https://github.com/ynput/ayon-traypublisher/pull/71
1. Publish some `ociolook` product via the TrayPublisher (https://github.com/ynput/ayon-traypublisher/pull/71)
2. Load the resulting product in Nuke through the loader
> Make ocioLook loader handle multiple chained LUTs.

- client/ayon_nuke/api/lib.py
- client/ayon_nuke/startup/custom_write_node.py
- server/settings/imageio.py
Re-adding possibility to to specify custom node classes in node overrides. #43 turned node classes to enum but that removed ability to specify any other class than those listed there. Also changed usage of "subset" to "product" as mentioned in #70
1. Create new override `ayon+settings://nuke/imageio/nodes/override_nodes` targeting node class not listed in the **Nuke Node Class** enum.
2. See if the override was applied
Closes #70
Closes #84 
Closes #26 
[AY-5776](https://app.clickup.com/t/6658547/AY-5776)
> Add custom node classes and change subset to product

- client/ayon_nuke/api/lib.py
- client/ayon_nuke/api/plugin.py
- client/ayon_nuke/plugins/publish/collect_writes.py
- client/ayon_nuke/plugins/publish/extract_render_local.py
- client/ayon_nuke/plugins/publish/validate_write_nodes.py
- client/ayon_nuke/startup/custom_write_node.py
resolve: https://github.com/ynput/ayon-nuke/issues/69
resolve: https://github.com/ynput/ayon-nuke/issues/72
Changes to ensure SXR (exr) and JPG (jpeg) can be rendered out of our `Render` write nodes through AYON settings.
Needs to be tested with https://github.com/ynput/ayon-core/pull/1165 to ensure loader is OK.
Current implementation in Nuke assumes that `file_type` and output file extension are always matching.
However Nuke has some disperencies here:
* file extension: jpg / file_type: jpeg
* file extension: sxr / file_type: exr
These changes ensure extension is set from an `ext` knob if defined, then computed from the `path` knob.
Render SXR output:
1. Set `Render (write)` node knobs settings (`ayon+settings://nuke/imageio/nodes/required_nodes/0/knobs`) to:
* `file_type` : exr (Text) …
> AY-7442 Dissociate file_type and ext knob computation (SXR and JPG extension support).

- client/ayon_nuke/api/lib.py
- client/ayon_nuke/startup/custom_write_node.py
- server/settings/conversion.py
- server/settings/imageio.py
#85 was merged before settings conversion could be added. This is adding conversion function that converts `subsets` to `product_names` so project overrides can be copyied.
1. Create project overrides in older ayon-nuke addons on `ayon+settings://nuke/imageio/nodes/override_nodes`. Add something to *subsets*
2. Switch to this ayon-nuke version
3. Copy project overrides from previous version
> add settings conversion for #85

- server/settings/conversion.py
PR #88 introduced debug log to conversion function utilizing logger from server backend. This unfortunately created dependency to new server version just because of this.  This PR is removing this import so it stays as much compatible as possible with older versions.
Addon shouldn't fail on older (but declared compatible) version of the server
> Fix: remove unnecessary logger import

- client/ayon_nuke/plugins/load/load_backdrop.py
Allow loading any `.nk` file with `LoadBackdropNodes`
Not sure if there's reason to do this or not - but it came up recently that matte shapes from e.g. Silhouette couldn't be loaded otherwise. Didn't test whether this is the valid approach to loading that data however.
1. Importing other `.nk` products makes sense?
2. Importing should work.
> Allow loading any `.nk` file with `LoadBackdropNodes`

- client/ayon_nuke/api/push_to_project.py
- client/ayon_nuke/plugins/publish/extract_headless_farm.py
Use `get_current_workfile` instead of `current_workfile`, `open_workfile` instead of `open_file` and `save_workfile` instead of `save_file`.
Method `current_workfile` is deprecated for years now.
Not sure how to test changed places.
> Chore: Don't use deprecated workfile method

- client/ayon_nuke/plugins/publish/collect_writes.py
[Here](https://github.com/ynput/ayon-nuke/issues/123) the related issue.
Issue comes from the following line: 
```
slate_frame = collected_frames[0].replace(
frame_start_str, frame_slate_str)
```
Since `collected_frames` was not sorted, the first element (`collected_frames[0]`) does not match the value of `frame_start_str` (which in our case corresponds to 1001). Therefore, replacing that value did not work and the following line `collected_frames.insert(0, slate_frame)` introduced whichever element is at `collected_frames[0]`. 
For instance, in our test, the first element was frame 1017 and `collected_frames` ended up being like this: 
```
COLLECTED FRAMES -> ['renderScanCheckMain.1017.exr', 'renderScanCheckMain.1017.exr', 'renderScanCheckMain.1051.exr',  ... ]
```
We now look for …
> Fix wrong frame being integrated as slate frame

- client/ayon_nuke/plugins/publish/extract_render_local.py
Extract Render Local: Raise `PublishError` on render failure to execute the node for rendering so that more meaningful hint is given in publisher UI.
closes https://github.com/ynput/ayon-nuke/issues/126
[AY-7997](https://app.clickup.com/t/86c4amk6c)
1. Set up a node graph where Writer render would fail (e.g. have failing Reader as input)
2. The publisher UI should show a more meaningful error message with some more information.
> AY-7997_Extract Render Local: Raise `PublishError` on render failure

- client/ayon_nuke/plugins/load/actions.py
- client/ayon_nuke/plugins/load/load_clip.py
Alllow `handleStart` and `handleEnd` to be `None` on version.
Attributes `handleStart` and `handleEnd` are always filled but can be filled with `None`. The handling method `get` would be working only if the attribute would not be available on version. The change works for both `None` and `0`.
1. Plates without filled `handleStart` or `handleEnd` filled on version can be loaded.
> Load: Handles on version can be unset

- client/ayon_nuke/plugins/create/create_backdrop.py
Remove `maintain_selection` attribute. It does nothing.
This attribute only existed due to inheriting it from the legacy creators before switching to the new publisher (where it used to go through code like [this](https://github.com/ynput/ayon-core/blob/c2f3d8b114ecd93871029144bc81a77ad841758e/client/ayon_core/pipeline/create/legacy_create.py#L208)). However, I am pretty sure now it's unused.
Equivalent to:
- https://github.com/ynput/ayon-blender/pull/138
- https://github.com/ynput/ayon-houdini/pull/282
1. Creator should not be affected.
> Create Backdrop: Remove `maintain_selection` attribute.
